### ISSUE TITLE
What is the linux password?

### ISSUE THREAD

**Issue by osaddict** [jonasrosland/vagrant-scaleio#7]
Since I'm on a mac, it would be great if I should ssh to one of the linux nodes, but I can't figure out what the password is for the linux VMs. 

BTW, this is wicked cool!

**Comment by swevm** [comment]
You can use 'vagrant ssh mdm1' to open a ssh session without needing a password. Replace mdm1 with 'tb' or 'mdm2' to get to the other two defined VMs. 

Btw Default root password is 'vagrant' which work as well.

**Comment by osaddict** [comment]
Sweet! Can you add that info the Readme?

**Comment by jonasrosland** [comment]
Hi osaddict! That is standard behaviour for all Vagrant setups, but I'll add it to the readme for more clarity.
Thanks!
